Mades blog changes to the cloned copy.

diff --git a/CloudFormation/ib_builder.yml b/CloudFormation/ib_builder.yml
--- a/CloudFormation/ib_builder.yml
+++ b/CloudFormation/ib_builder.yml
@@ -2,6 +2,23 @@
 # SPDX-License-Identifier: MIT-0
 AWSTemplateFormatVersion: 2010-09-09
 
+Parameters:
+  CustomSubnetId:
+    Type: String
+    Default: ""
+    Description: If you do not have a default VPC, or want to use a different VPC, specify the ID of a subnet in which to place the instance used to customize your EC2 AMI. If not specified, a subnet from your default VPC will be used.
+  CustomSecurityGroupId:
+    Type: CommaDelimitedList
+    Default: ""
+    Description: Required if you specified a custom subnet ID. Comma-delimted list of one or more IDs of security groups belonging to the VPC to associate with the instance used to customize your EC2 AMI.
+  BuildInstanceType:
+    Type: CommaDelimitedList
+    Default: "t2.micro"
+    Description: Comma-delimited list of one or more instance types to select from when building the image. Image Builder will select a type based on availability. The supplied default is compatible with the AWS Free Tier.
+
+Conditions:
+  UseCustomSubnetId: !Not [ !Equals [ !Ref CustomSubnetId, "" ] ]
+
 Resources:
   # Create an S3 Bucket for logs.
   # When deleting the stack, make sure to empty the bucket first.
@@ -46,7 +63,7 @@ Resources:
       Roles:
         - Ref: InstanceRole
       PolicyDocument:
-        Version: 2012-10-17
+        Version: "2012-10-17"
         Statement:
           - Action:
               - s3:PutObject
@@ -69,134 +86,154 @@ Resources:
 
   # Specifies the infrastructure within which to build and test your image.
   # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-infrastructureconfiguration.html
-  WindowsServer2016ImageInfrastructureConfiguration:
+  UbuntuServer20ImageInfrastructureConfiguration:
     Type: AWS::ImageBuilder::InfrastructureConfiguration
     Properties:
-      Name: WindowsServer-2016-VSCode-Image-Infrastructure-Configuration
+      Name: UbuntuServer20-Image-Infrastructure-Configuration
       InstanceProfileName:
         Ref: InstanceProfile
+      # Set of one or more instance types to use when building the instance. Image Builder will select a type
+      # based on availability.
+      InstanceTypes:
+        Ref: BuildInstanceType
       # Specify an S3 bucket and EC2 Image Builder will save logs to the bucket.
       Logging:
         S3Logs:
           S3BucketName:
             Ref: ImageBuilderLogBucket
-          # S3KeyPrefix: 'my-imagebuilder-bucket-prefix'
+          S3KeyPrefix: !Join [ "-", [ 'imagebuilder', !Ref "AWS::StackName" ] ]
       # If you would like to keep the instance running after a failed build, set TerminateInstanceOnFailure to false.
       # TerminateInstanceOnFailure: false
-      # If you do not have a default VPC or want to use a different VPC, you must specify the subnet ID to use
-      # SubnetId: 'subnet-id'
+      # If you do not have a default VPC or want to use a different VPC, you must specify the IDs of a subnet and one or more
+      # security groups to be associated with the build instance.
+      SubnetId: !If [ UseCustomSubnetId, !Ref CustomSubnetId , !Ref "AWS::NoValue" ]
+      SecurityGroupIds:
+        - !If [ UseCustomSubnetId, !Ref CustomSecurityGroupId , !Ref "AWS::NoValue" ]
 
-  # Create a custom EC2 Image Builder component that downloads and installs Visual Studio Code. The component includes a
+  # Create a custom EC2 Image Builder component that downloads and installs the latest .NET 5 preview. The component includes a
   # validation step which will run after the install but before the image capture. Also included, is a test step which
   # runs after the image is captured (EC2 Image Builder launches a new instance from the image and runs the test phase).
   # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-component.html
-  VisualStudioCodeComponent:
+  InstallNET5Component:
     Type: AWS::ImageBuilder::Component
     Properties:
-      Name: VisualStudioCode
+      Name: NET5
       Version: 0.0.1
-      Description: Install Visual Studio Code
+      Description: Install the latest .NET 5 preview.
       ChangeDescription: First version
-      Platform: Windows
+      Platform: Linux
       Data: |
-        name: InstallVSCode
-        description: Downloads and Installs Visual Studio Code
+        name: InstallNET5
+        description: Downloads and Installs the latest .NET 5 preview
         schemaVersion: 1.0
-
+        constants:
+          - InstallScriptSource:
+              type: string
+              value: https://aka.ms/install-dotnet-preview
+          - Version:
+              type: string
+              value: '5.0'
         phases:
           - name: build
             steps:
-              - name: VSCodeInstall
-                action: ExecutePowerShell
+              - name: InstallFolder
+                action: ExecuteBash
                 inputs:
                   commands:
-                    - |
-                      # Set TLS 1.2 for Invoke-RestMethod
-                      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
-
-                      # Set the download link to Visual Studio Code (64-bit installer)
-                      $downloadUrl = "https://go.microsoft.com/fwlink/?Linkid=852157"
-
-                      # Set the path for our download, which will be in the temp directory
-                      $installerFile = "vscode-install.exe"
-                      $installerDownloadPath = (Join-Path $env:TEMP $installerFile)
-
-                      # Set Install Options
-                      # Include the context menu, file association, and add to path options (and don't run code after install:
-                      $installerArguments = '/verysilent /mergetasks=!runcode,addcontextmenufiles,addcontextmenufolders,associatewithfiles,addtopath'
-
-                      # Download the file
-                      Invoke-Webrequest $downloadUrl -UseBasicParsing -OutFile $installerDownloadPath
-
-                      # Install
-                      Start-Process $installerDownloadPath -ArgumentList $installerArguments -Wait
-
-                      # Cleanup
-                      Remove-Item $installerDownloadPath -Force
+                    - echo "$HOME/dotnet_install"
+              - name: CreateInstallFolder
+                action: CreateFolder
+                inputs:
+                  - path: '{{ build.InstallFolder.outputs.stdout }}'
+              - name: DownloadInstallScript
+                action: WebDownload
+                inputs:
+                  - source: '{{ InstallScriptSource }}'
+                    destination: '{{ build.InstallFolder.outputs.stdout }}/install.sh'
+              - name: InstallNET5
+                action: ExecuteBash
+                inputs:
+                  commands:
+                    - 'set -e'
+                    - 'cd {{ build.InstallFolder.outputs.stdout }}'
+                    - 'sudo bash install.sh'
+              - name: Cleanup
+                action: DeleteFolder
+                inputs:
+                  - path: '{{ build.InstallFolder.outputs.stdout }}'
+                    force: true
 
           - name: validate
             steps:
-              - name: VSCodeValidate
-                action: ExecutePowerShell
+              - name: ValidateRuntimeInstall
+                action: ExecuteBash
                 inputs:
                   commands:
                     - |
-                      $installed = Test-Path (Join-Path $env:ProgramFiles "Microsoft VS Code\Code.exe")
-                      if (-not $installed)
-                      {
+                      VERSION='{{ Version }}'
+                      echo "Invoking command: dotnet --list-runtimes | grep \"^Microsoft.NETCore.App $VERSION\""
+                      EXISTS=$(dotnet --list-runtimes | grep "^Microsoft.NETCore.App $VERSION")
+                      if [[ $? == 0 ]]; then
+                        echo "Found .NET runtime version $VERSION. Proceeding."
+                      else
+                        echo "Unable to find .NET runtime version $VERSION. Failing build."
                         exit 1
-                      }
-
-          - name: test
-            steps:
-              - name: VSCodeTest
-                action: ExecutePowerShell
+                      fi
+              - name: ValidateSDKInstall
+                action: ExecuteBash
                 inputs:
                   commands:
                     - |
-                      try {
-                        code --version
-                      }
-                      catch
-                      {
+                      VERSION='{{ Version }}'
+                      echo "Invoking command: dotnet --list-sdks | grep \"^$VERSION\""
+                      EXISTS=$(dotnet --list-sdks | grep "^$VERSION")
+                      if [[ $? == 0 ]]; then
+                        echo "Found .NET SDK version $VERSION. Proceeding."
+                      else
+                        echo "Unable to find .NET SDK version $VERSION. Failing build."
                         exit 1
-                      }
+                      fi
 
-  # Recipe which references the latest (x.x.x) version of Windows Server 2016 English AMI with Desktop Experience).
+  # Recipe which references the latest (x.x.x) version of Ubuntu Server 20 AMI.
   # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html
-  WindowsServer2016ImageRecipe:
+  UbuntuServer20NET5ImageRecipe:
     Type: AWS::ImageBuilder::ImageRecipe
     Properties:
-      Name: Windows_Server-2016-VisualStudioCode
+      Name: UbuntuServer20NET5
       Version: 0.0.1
       # ${AWS::Partition} returns the partition where you are running the CloudFormation template. For standard AWS regions, the
       # partition is aws. For resources elsewhere, the partition is aws-partitionname. For example, China (Beijing and Ningxia)
       # regions use aws-cn and AWS GovCloud (US) regions are aws-us-gov.
       # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
       ParentImage:
-        Fn::Sub: arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:image/windows-server-2016-english-full-base-x86/x.x.x
+        Fn::Sub: arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:image/ubuntu-server-20-lts-x86/x.x.x
       Components:
         - ComponentArn:
-            Ref: VisualStudioCodeComponent
+            Ref: InstallNET5Component
 
   # The Image resource will show complete in CloudFormation once your image is done building. Use this resource later in your
   # stack to reference the image within other resources.
   # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-image.html
-  WindowServer2016WithVisualStudioCode:
+  UbuntuServer20WithNET5:
     Type: AWS::ImageBuilder::Image
     Properties:
       ImageRecipeArn:
-        Ref: WindowsServer2016ImageRecipe
+        Ref: UbuntuServer20NET5ImageRecipe
       InfrastructureConfigurationArn:
-        Ref: WindowsServer2016ImageInfrastructureConfiguration
+        Ref: UbuntuServer20ImageInfrastructureConfiguration
 
   # Create an SSM Parameter Store entry with our resulting ImageId.
   # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
-  WindowServer2016WithVisualStudioCodeParameter:
+  UbuntuServer20WithNET5Parameter:
     Type: AWS::SSM::Parameter
     Properties:
-      Description: Image Id for Window Server 2016 With Visual Studio Code
-      Name: /Test/Images/Windows_Server-2016-VisualStudioCode
+      Description: Image Id for Ubuntu Server 20 With latest .NET 5 preview
+      Name: /Test/Images/UbuntuServer20WithNET5
       Type: String
       Value:
-        Fn::GetAtt: [WindowServer2016WithVisualStudioCode, ImageId]
+        Fn::GetAtt: [UbuntuServer20WithNET5, ImageId]
+
+Outputs:
+  SSMParam:
+    Description: This is a Parameter stored on AWS Systems Manager Parameter Store
+    Value: !Ref UbuntuServer20WithNET5Parameter
